name: ecoin
description: "Educational ecology app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  another_flushbar: ^1.12.30
  auto_route: ^8.1.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  iconsax_plus: ^1.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  logger: ^2.2.0
  sizer: ^2.0.15
  skeletonizer: ^1.1.2+1
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/core/
    - assets/onboarding/
    - assets/home/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/core/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/core/logo.png

  android_12:
    image: assets/core/logo.png
    icon_background_color: "#ffffff"

  web: false